# Use openjdk as the base image
FROM openjdk:8-jdk-alpine

# Set the working directory
WORKDIR /app

# Copy the backend files
COPY . .

# Build the backend
RUN mvn clean install

# Expose the port
EXPOSE 8080

# Start the server
CMD ["java", "-jar", "target/pubtalkapp.jar"]



#FROM openjdk:8-jdk-alpine
#COPY target/pubtalkapp-0.0.1-SNAPSHOT.jar app.jar
#EXPOSE 8080
#ENTRYPOINT ["java","-jar","/app.jar"]

