version: '3'
services:
  frontend:
    build:
      context: ./appfrontend
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
#    command:
#      - ng serve --host docker.host.internal -poll=1000
  backend:
    build:
      context: ./appbackend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
#    command:
#      - java -jar ./appbac
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pubtalkapp
      - DATABASE_URL=jdbc:postgresql://db:5432/pubtalkapp
    ports:
      - "5432:5432"
    hostname: postgres
