version: '3'
services:
  frontend:
    build:
      context: ./appfrontend
    container_name: pta_frontend
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
#    command:
#      - ng serve --host docker.host.internal -poll=1000
  backend:
    build:
      context: ./appbackend
    container_name: pta_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pubtalkapp
#    command:
#      - java -jar ./appbac
    depends_on:
      - db
  db:
    image: postgres
    container_name: pta_db
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pubtalkapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
