#version: 0.2
#
#env:
#  variables:
#    APP_NAME: "e-commerce"
#phases:
#  install:
#    runtime-versions:
#      nodejs: 16.x
#    commands:
#      - echo install process started
#      - npm install --legacy-peer-deps
#  build:
#    commands:
#      - echo build process started now
#      - npx ng build
#  post_build:
#    commands:
#      - echo build process finished, we should upload to S3 now
#      - cd dist/$APP_NAME
#      - ls -la
#      - aws s3 sync . s3://propanegaming




#version: 0.2
#
#phases:
#  pre_build:
#    commands:
#      - echo Logging in to Amazon ECR...
#      - aws --version
#      - $(aws ecr get-login --no-include-email --region us-west-2)
#  build:
#    commands:
#      - echo Build started on `date`
#      - npm install
#      - ng build --prod
#  post_build:
#    commands:
#      - echo Build completed on `date`
#      - echo Pushing the Docker image...
#      - docker build -t pubtalkapp-frontend:latest .
#      - docker tag pubtalkapp-frontend:latest 1234567890.dkr.ecr.us-west-2.amazonaws.com/pubtalkapp-frontend:latest
#      - docker push 1234567890.dkr.ecr.us-west-2.amazonaws.com/pubtalkapp-frontend:latest

