###
// TRACX REQUESTS
###

GET http://localhost:8080/api/v1/tracks/all
Accept: application/json

<> 2023-01-11T161830.200.json
<> 2023-01-11T161625.200.json
<> 2023-01-11T161423.200.json

###

POST http://localhost:8080/api/v1/tracks/add
Content-Type: application/json

{
  "trackName": "New Track",
  "trackImageUrl": "https://i0.wp.com/cms.babbel.news/wp-content/uploads/2017/10/CM_MagazineHeader_Gaga.png",
  "trackLength": 55242
}

<> 2023-01-11T161831.201.json
<> 2023-01-11T161625.201.json
<> 2023-01-11T161423.201.json

###

PUT http://localhost:8080/api/v1/tracks/update
Content-Type: application/json

{
  "id": 1,
  "trackName": "Updated Track Name",
  "trackImageUrl": "https://i0.wp.com/cms.babbel.news/wp-content/uploads/2017/10/CM_MagazineHeader_Gaga.png",
  "trackUrl": "./assets/static/audio/test/Release.mp3",
  "trackLength": 256
}

<> 2023-01-11T161831-1.201.json
<> 2023-01-11T161626.201.json
<> 2023-01-11T161423-1.201.json


###
// ARTIST REQUESTS
###

GET http://localhost:8080/api/v1/artists/all
Accept: application/json

<> 2023-01-11T161831.200.json
<> 2023-01-11T161626.200.json
<> 2023-01-11T161423-1.200.json


###
POST http://localhost:8080/api/v1/artists/add
Content-Type: application/json

{
  "artistName": "'Ol Boy",
  "artistImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4fBGnid94mnWO3M2h847ztbXzRVeXw8935rzOHFcZOaaj0luxUuzMMnv8ud4PytEVZoI&usqp=CAU",
  "pro": "SESAC",
  "proIPI": "8513776"
}

<> 2023-01-11T161831-2.201.json
<> 2023-01-11T161626-1.201.json
<> 2023-01-11T161423-2.201.json

###
POST http://localhost:8080/api/v1/artists/add
Content-Type: application/json

{
  "id": "1",
  "artistName": "'Ol Boy",
  "artistImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4fBGnid94mnWO3M2h847ztbXzRVeXw8935rzOHFcZOaaj0luxUuzMMnv8ud4PytEVZoI&usqp=CAU",
  "pro": "BMI",
  "proIPI": "8513776",
  "artistTracks": [
    {
      "trackName": "Updated Name Again",
      "trackImageUrl": "https://i0.wp.com/cms.babbel.news/wp-content/uploads/2017/10/CM_MagazineHeader_Gaga.png",
      "trackUrl": "./assets/static/audio/test/Release.mp3",
      "trackLength": 256,
      "artist": []
    }
  ],
  "artistProjects": [
    {
      "projectName": "Glued Down",
      "projectImageUrl": "https://media.redbullmusicacademy.com/assets/Black_Milk_by_Maxwell_Schiano-2.132b8df9.jpg",
      "numOfTracks": 38,
      "projectLength": 888
    }
  ]
}

<> 2023-01-11T161831-3.201.json
<> 2023-01-11T161626-2.201.json
<> 2023-01-11T161423-3.201.json

###
// PROJECT REQUESTS
###

GET http://localhost:8080/api/v1/projects/all
Accept: application/json

<> 2023-01-11T161831-1.200.json
<> 2023-01-11T161626-1.200.json
<> 2023-01-11T161423-2.200.json

###

POST http://localhost:8080/api/v1/projects/add
Content-Type: application/json

{
  "projectName": "Glued Up",
  "projectImageUrl": "https://media.cnn.com/api/v1/images/stellar/prod/210208082052-01-gorilla-glue-harispray.jpg?q=x_0,y_0,h_947,w_1682,c_fill/h_720,w_1280",
  "numOfTracks": 38,
  "projectLength": 888
}

<> 2023-01-11T161831-4.201.json
<> 2023-01-11T161626-3.201.json
<> 2023-01-11T161424.201.json
<> 2023-01-11T151756-1.201.json

###

PUT http://localhost:8080/api/v1/projects/update
Content-Type: application/json

{
  "id": 1,
  "projectName": "Glued Down",
  "projectImageUrl": "https://media.redbullmusicacademy.com/assets/Black_Milk_by_Maxwell_Schiano-2.132b8df9.jpg",
  "numOfTracks": 38,
  "projectLength": 888
}

<> 2023-01-11T161831-5.201.json
<> 2023-01-11T161626-4.201.json
<> 2023-01-11T161424-1.201.json
<> 2023-01-11T151756-2.201.json

###
// ADDING ARTISTS TO TRACKS
###

GET http://localhost:8080/api/v1/tracks/all
Accept: application/json

<> 2023-01-11T161831-2.200.json
<> 2023-01-11T161626-2.200.json
<> 2023-01-11T161424.200.json
<> 2023-01-11T160600.200.json
<> 2023-01-11T155438.200.json
<> 2023-01-11T154314.200.json
<> 2023-01-11T153722.200.json

###

// Adding new Artist to existing Track
PUT http://localhost:8080/api/v1/tracks/update
Content-Type: application/json

{
  "id": 1,
  "trackName": "Updated Track Name",
  "trackImageUrl": "https://i0.wp.com/cms.babbel.news/wp-content/uploads/2017/10/CM_MagazineHeader_Gaga.png",
  "trackUrl": "./assets/static/audio/test/Release.mp3",
  "trackLength": 256,
  "artist": [
    {
      "artistName": "One Too Many",
      "artistImageUrl": "https://i1.sndcdn.com/artworks-xVvWQxMKwDrOz2fu-mSeoyg-t500x500.jpg",
      "pro": "ASCAP",
      "proIPI": "159753"
    }
  ],
  "project": []
}

<> 2023-01-11T161831-6.201.json
<> 2023-01-11T161626-5.201.json
<> 2023-01-11T161424-2.201.json
<> 2023-01-11T154533.201.json
<> 2023-01-11T154303.201.json

###

// Creating a new Track with existing Artist
PUT http://localhost:8080/api/v1/tracks/update
Content-Type: application/json

{
  "trackName": "It's What I Said",
  "trackImageUrl": "https://i.stack.imgur.com/V5PSe.jpg",
  "trackUrl": "./assets/static/audio/test/Release.mp3",
  "trackLength": 127,
  "artist": [
    {
      "artistName": "'Ol Boy",
      "artistImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4fBGnid94mnWO3M2h847ztbXzRVeXw8935rzOHFcZOaaj0luxUuzMMnv8ud4PytEVZoI&usqp=CAU",
      "pro": "BMI",
      "proIPI": "8513776"
    }
  ],
  "project": []
}

<> 2023-01-11T161831.500.json
<> 2023-01-11T161626.500.json
<> 2023-01-11T161424.500.json
<> 2023-01-11T161346.201.json
<> 2023-01-11T160256.201.json

###

// Creating a new Track with new Artist
POST http://localhost:8080/api/v1/tracks/add
Content-Type: application/json

{
  "trackName": "Wait A Minute",
  "trackImageUrl": "https://cdns-images.dzcdn.net/images/artist/c91f64406a39cb441e860aa25dcb97e3/500x500.jpg",
  "trackUrl": "./assets/static/audio/test/Release.mp3",
  "trackLength": 85,
  "artist": [
    {
      "artistName": "Blu Tew",
      "artistImageUrl": "https://www.billboard.com/wp-content/uploads/2022/04/Willow-cr-Dana-Trippe-press-2022-billboard-1548.jpg",
      "pro": "BMI",
      "proIPI": "673198"
    }
  ]
}

<> 2023-01-11T161832.201.json
<> 2023-01-11T161626-6.201.json
<> 2023-01-11T161424-3.201.json
<> 2023-01-11T155236.201.json




